<?php
/**
 * @file
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\reposi_apiscopus\Controller\reposidoc_scopus;

function _reposi_apiscopus_user_role_administrator() {
  global $user;
  $roles = array('administrator');
  foreach ($roles as $role) {
    if (in_array($role, $user->roles)) {
      return TRUE;
    }
  }
  return FALSE;
}

function reposi_cron(){

$config = \Drupal::config('system.maintenance');
$reposi_apiscopus_cron = $config->get('reposi_apiscopus_cron');
if (isset($reposi_apiscopus_cron)) {
		if ($reposi_apiscopus_cron == 1){
			$less_month = 1*3600*24*30;
		} elseif ($reposi_apiscopus_cron == 2){
			$less_month = 3*3600*24*30;
		} elseif ($reposi_apiscopus_cron == 3){
			$less_month = 6*3600*24*30;
		}
	} else {
		$less_month = 12*3600*24*30;
	}

  $estae=\Drupal::state()->get('date_now_scopus');

  if (!isset($estae) ){
    $date_now=\Drupal::time()->getRequestTime();
    \Drupal::state()->set('date_now_scopus',$date_now);
    $date_event=$date_now+$less_month;
    \Drupal::state()->set('date_event_scopus',$date_event);
  }

  $datete=\Drupal::state()->get('date_event_scopus');
  $date=\Drupal::time()->getRequestTime();
  $stateless=\Drupal::state()->get('date_event_scopus_1');
if ( ($datete<=$date) || ($stateless!=$reposi_apiscopus_cron) ){
  $date_now=\Drupal::time()->getRequestTime();
  reposidoc_scopus::docs_scopus(0, \Drupal::time()->getRequestTime());
  \Drupal::state()->set('date_now_scopus',$date_now);
  $date_event=$date_now+$less_month;
  \Drupal::state()->set('date_event_scopus',$date_event);
}
\Drupal::state()->set('date_event_scopus_1',$reposi_apiscopus_cron);
$time_for_event=floor(($datete-$date)/(3600*24));
drupal_set_message("Next event Apiscopus in ".$time_for_event." days");
}
